name       : efibootmgr
version    : '18'
release    : 2
source     :
    - https://github.com/rhboot/efibootmgr/releases/download/18/efibootmgr-18.tar.bz2 : 2b195f912aa353f0d11f21f207684c91460fbc37f9a4f2673e63e5e32d108b10
license    : GPL-2.0-only
component  : system.utils
summary    : a Linux user-space application to modify the Intel Extensible Firmware Interface (EFI) Boot Manager
description: |
    a Linux user-space application to modify the Intel Extensible Firmware Interface (EFI) Boot Manager
builddeps  :
    - pkgconfig(efivar)
    - pkgconfig(popt)
environment: |
    export GCC_IGNORE_WERROR=1
build      : |
    %make EFIDIR=/
install    : |
    %make_install EFIDIR=/
