name       : efibootmgr
version    : 14
release    : 1
source     :
    - https://github.com/rhinstaller/efibootmgr/releases/download/14/efibootmgr-14.tar.bz2 : 377ec16484414b80afd1b8a586153d7ef55ccf048638080101d49b7c77f37ad8
license    : GPL-2.0
component  : system.utils
summary    : a Linux user-space application to modify the Intel Extensible Firmware Interface (EFI) Boot Manager
description: |
    a Linux user-space application to modify the Intel Extensible Firmware Interface (EFI) Boot Manager
builddeps  :
    - pkgconfig(efivar)
    - pkgconfig(popt)
build      : |
    %make
install    : |
    %make_install
